New argument handling

diff --git a/download b/download
--- a/download
+++ b/download
@@ -1,26 +1,34 @@
 #!/usr/bin/env bash
 
-USAGE="Usage: $(basename "$0") <FILE>";
+USAGE="Usage: $(basename "$0") [OPTION]... FILE";
 
-# Need to change this methodology when argument handling changes to accommodate more options
-NUM_ARGS=1;
-
-# Need to change when flags can be set to specify start point
+# Will change if argument is passed to specify alternate start point
+series_name="";
 season=1;
 episode=1;
 
+# Program arguments (short)
+SHORT=s:e:n:
+# Program arguments (long)
+LONG=season:,episode:,name:
+
 # Error codes
-E_MISSING_ARGS=1;
+E_INVALID_ARGS=1;
 E_MISSING_FILE=2;
 E_EMPTY_FILE=3; 
+E_GETOPT_FAIL=4;
 
 # Regex for capturing the episode number from the URL
 EPS_NUMBER_REGEX="_([0-9]+)\.mp4$";
+# Regex for capturing the episode number (HD) from the URL
+EPS_NUMBER_HD_REGEX="_([0-9]+)_hd\.mp4$";
 # Regex for matching against invalid directory names
 INVALID_DIR_REGEX="/";
+# Regex matching line containing only numbers
+NUMERIC_LINE_REGEX="^[0-9]+$";
 
 # Gets the series name from the user.
-# Fails if an invalid name is used or if the name matches and existing directory.
+# Auto-retry if an invalid name is used or if the name matches and existing directory.
 get_series_name() {
     read -r -p "Enter series name: " series_name;
 
@@ -29,35 +37,99 @@ get_series_name() {
         get_series_name
     fi
 
-    if [ -d "$series_name" ]; then
+    if [[ -d "$series_name" ]]; then
         echo "Series name matches existing directory. Try again.";
         get_series_name
     fi
 }
 
-# If an invalid number of arguments are passed in.
-if [ $# != "$NUM_ARGS" ]; then
+if [[ $# -eq 0 ]]; then
     echo "$USAGE";
-    exit "$E_MISSING_ARGS";
+    exit "$E_INVALID_ARGS";
 fi
 
+getopt --test > /dev/null
+if [[ $? -ne 4 ]]; then
+    echo "$0: Fatal error. getopt --test failed.";
+    exit "$E_GETOPT_FAIL";
+fi
+
+if ! PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@"); then
+    # Wrong argument error has been printed to stdout, time to fail
+    exit "$E_INVALID_ARGS";
+fi
+
+eval set -- "$PARSED";
+
+while true; do
+    case "$1" in
+        -s|--season)
+            if [[ ! "$2" =~ $NUMERIC_LINE_REGEX ]]; then
+                echo "$0: Invalid season number.";
+                exit "$E_INVALID_ARGS";
+            fi
+
+            season="$2";
+
+            shift 2;
+            ;;
+        -e|--episode)
+            if [[ ! "$2" =~ $NUMERIC_LINE_REGEX ]]; then
+                echo "$0: Invalid episode number.";
+                exit "$E_INVALID_ARGS";
+            fi
+
+            episode="$2";
+
+            shift 2;
+            ;;
+        -n|--name)
+            if [[ "$2" =~ $INVALID_DIR_REGEX ]]; then
+                echo "$0: Invalid character in series name.";
+                exit "$E_INVALID_ARGS";
+            fi
+
+            series_name="$2";
+
+            shift 2;
+            ;;
+        --)
+            shift;
+            break;
+            ;;
+        *)
+            echo "$0: Fatal error while parsing arguments. Report this bug.";
+            exit "$E_INVALID_ARGS";
+            ;;
+    esac
+done
+
+if [[ $# -eq 0 ]]; then
+    echo "$0: An input file is required.";
+    exit "$E_INVALID_ARGS";
+fi
+
+# Validate input file
+# TODO: Validate URLs in the input file
 # If the input file doesn't exist or is empty
-if [ ! -s "$1" ]; then
+if [[ ! -s "$1" ]]; then
     # If the input file doesn't exist
-    if [ ! -f "$1" ]; then
-        echo "Error: Cannot locate file $1.";
+    if [[ ! -f "$1" ]]; then
+        echo "$0: Cannot locate file $1.";
         exit "$E_MISSING_FILE";
     else
         # File exists but is empty
-        echo "Error: File $1 is empty. Nothing to do.";
+        echo "$0: File $1 is empty. Nothing to do.";
         exit "$E_EMPTY_FILE";
     fi
 fi
 
-get_series_name
+if [[ "$series_name" == "" ]]; then
+    get_series_name;
+fi
 
 # Create parent and first season directories
-mkdir -p ./"$series_name"/s1/;
+mkdir -p ./"$series_name"/s"$season"/;
 
 # While the input file has another URL
 while IFS= read -r line || [[ -n "$line" ]]; do
@@ -75,12 +147,14 @@ while IFS= read -r line || [[ -n "$line" ]]; do
     # If no match, set eps_number to -1 so we know later that we didn't match
     if [[ "$line" =~ $EPS_NUMBER_REGEX ]]; then
         eps_number="${BASH_REMATCH[1]}";
+    elif [[ "$line" =~ $EPS_NUMBER_HD_REGEX ]]; then
+        eps_number="${BASH_REMATCH[1]}";
     else
         eps_number=-1;
     fi
 
     # Generate the file name with proper season/epsiode labeling e.g. 01, 02, 03
-    if [ $eps_number -ne -1 ]; then
+    if [[ $eps_number -ne -1 ]]; then
         filename=$(printf "$series_name-s%02de%02d_%d.mp4\n" "$season" "$episode" "$eps_number");
     else
         # We didn't find an episode number, don't include it in the file name
